/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guiexercise1;

import java.util.Scanner;
import java.io.*;

/**
 *
 * @author roanm
 */
public class GUIExercise1 extends javax.swing.JFrame {

    /**
     * Creates new form GUIExercise1Frame
     */
    public GUIExercise1() {
        initComponents();
    }
    
        private static String[] nouns = loadFile("/Users/roanm/Documents/Computer Science/ICS4U/GUIExercises/GUIExercise1/src/guiexercise1/nouns.txt");
        private static String[] verbs = loadFile("/Users/roanm/Documents/Computer Science/ICS4U/GUIExercises/GUIExercise1/src/guiexercise1/verbs.txt");
        private static String[] sentences = loadFile("/Users/roanm/Documents/Computer Science/ICS4U/GUIExercises/GUIExercise1/src/guiexercise1/sentences.txt");

    
    public static String[] loadFile(String path) {
        String[] contents = null;
        try {
            File f = new File(path);
            Scanner s = new Scanner(f);
            contents = new String[10];
            int i = 0;
            while (s.hasNextLine()) {
                contents[i] = s.nextLine();
                i++;
            }
        } catch (Exception e) {
            System.out.println("Error: "+e);
        }
        return contents;
        
        
    }
    
    public static String createSentence() {
        int randNum = (int)(Math.random()*10);
        String sentence =  sentences[randNum];
        
        while (sentence.contains("%")) {
            randNum = (int)(Math.random()*10);
            sentence = sentence.replaceFirst("%", verbs[randNum]);
        }
        while (sentence.contains("#")) {
            randNum = (int)(Math.random()*10);
            sentence = sentence.replaceFirst("#", nouns[randNum]);
        }
        return sentence;
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        madLibBtn = new javax.swing.JButton();
        outputLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ML");

        madLibBtn.setFont(new java.awt.Font("Cascadia Code", 0, 24)); // NOI18N
        madLibBtn.setText("Mad Lib!");
        madLibBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                madLibBtnActionPerformed(evt);
            }
        });

        outputLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(madLibBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addComponent(outputLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(outputLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(madLibBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void madLibBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_madLibBtnActionPerformed
        // TODO add your handling code here:
        String sentence = createSentence();
        outputLbl.setText(sentence);
        
        
        
    }//GEN-LAST:event_madLibBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIExercise1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIExercise1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIExercise1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIExercise1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>        
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIExercise1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton madLibBtn;
    private javax.swing.JLabel outputLbl;
    // End of variables declaration//GEN-END:variables
}
